contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/bbcvc/contribute
    about: Please read through before making contributions.
  - name: ğŸ’¬ Nobita's Discord Server
    url: https://discord.gg/Dd3ZtENvKG/
    about: Want to discuss / chat with the community? Here you go!
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://bbcvc.me/posts/why-reproductions-are-required
    about: Reproduction is very important for maintainer to help on your issues!
